apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
    - bookinfo.local
  gateways:
    - bookinfo-istio-gateway.apps-crc.testing
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
        port:
          number: 9080
      weight: 55
    - destination:
        host: productpage
        subset: v2
        port:
          number: 9080
      weight: 45